import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const API="https://v3.football.api-sports.io";
const CORS={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"GET, POST, OPTIONS"};
const out=(b:unknown,s=200)=>new Response(JSON.stringify(b,null,2),{status:s,headers:{...CORS,"Content-Type":"application/json"}});
async function api(path:string,key:string){const r=await fetch(API+path,{headers:{"x-apisports-key":key,Accept:"application/json"}});const text=await r.text();let d:any;try{d=JSON.parse(text)}catch{d={raw:text}}if(!r.ok)throw new Error(`HTTP ${r.status}: ${text.slice(0,500)}`);return d;}
const num=(v:any)=>{const n=Number(String(v??"").replace("%",""));return Number.isFinite(n)?n:null};
const clean=(v:any)=>String(v??"").trim();
Deno.serve(async(req:Request)=>{
 if(req.method==="OPTIONS")return new Response("ok",{headers:CORS});
 const key=Deno.env.get("API_FOOTBALL_KEY"),url=Deno.env.get("SUPABASE_URL"),service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY"),anon=Deno.env.get("SUPABASE_ANON_KEY")??"";
 if(!key||!url||!service||!anon)return out({ok:false,error:"Server configuration incomplete"},500);
 const ah=req.headers.get("Authorization")??"";if(!ah.startsWith("Bearer "))return out({ok:false,error:"Authorization Bearer JWT required"},401);
 const auth=createClient(url,anon,{auth:{persistSession:false,autoRefreshToken:false}});const {data:{user},error:ue}=await auth.auth.getUser(ah.slice(7));if(ue||!user)return out({ok:false,error:"Invalid or expired Supabase JWT"},401);
 const db=createClient(url,service,{auth:{persistSession:false,autoRefreshToken:false}});let b:any={};try{if(req.method==="POST")b=await req.json()}catch{}const q=new URL(req.url);const action=String(b.action??q.searchParams.get("action")??"");
 if(action==="prediction"||action==="odds"){const fixture=clean(b.fixture??q.searchParams.get("fixture"));if(!fixture)return out({ok:false,error:"fixture is required"},400);try{return out({ok:true,action,fixture,response:await api(`/${action==="prediction"?"predictions?fixture":"odds?fixture"}=${encodeURIComponent(fixture)}`,key)});}catch(e){return out({ok:false,action,fixture,error:e instanceof Error?e.message:String(e)},200)}}
 if(action!=="sync_analysis")return out({ok:false,error:"Unknown action",available_actions:["sync_analysis","prediction","odds"]},400);
 const ids=Array.isArray(b.fixture_ids)?b.fixture_ids.map(String).filter(Boolean).slice(0,30):[];if(!ids.length)return out({ok:false,error:"fixture_ids is required"},400);
 const {data:markets,error:me}=await db.from("markets").select("id,code").eq("is_active",true);if(me)return out({ok:false,error:`markets: ${me.message}`},200);const mids=new Map((markets??[]).map((m:any)=>[String(m.code),Number(m.id)]));
 const resolved:any[]=[];for(const raw of ids){const {data:m}=await db.from("matches").select("id,external_id,kickoff_at").eq("external_id",raw).maybeSingle();if(m)resolved.push(m)}
 let processed=0,predictionsSaved=0,oddsSaved=0,statsSaved=0;const errors:any[]=[],samples:any[]=[];
 for(const m of resolved){const ext=String(m.external_id);let pr:any=null,or:any=null,st:any=null;try{pr=await api(`/predictions?fixture=${encodeURIComponent(ext)}`,key)}catch(e){errors.push({fixture:ext,source:"predictions",error:e instanceof Error?e.message:String(e)})}try{or=await api(`/odds?fixture=${encodeURIComponent(ext)}`,key)}catch(e){errors.push({fixture:ext,source:"odds",error:e instanceof Error?e.message:String(e)})}try{st=await api(`/fixtures/statistics?fixture=${encodeURIComponent(ext)}`,key)}catch(e){errors.push({fixture:ext,source:"statistics",error:e instanceof Error?e.message:String(e)})}
  if(samples.length<3)samples.push({fixture:ext,prediction_response_items:Array.isArray(pr?.response)?pr.response.length:null,prediction_errors:pr?.errors??null,odds_response_items:Array.isArray(or?.response)?or.response.length:null,odds_errors:or?.errors??null,statistics_response_items:Array.isArray(st?.response)?st.response.length:null,statistics_errors:st?.errors??null});
  try{const pct=pr?.response?.[0]?.predictions?.percent;const pmid=mids.get("MATCH_RESULT");if(pct&&pmid){const rows:any[]=[];for(const x of [{s:"Home",v:pct.home},{s:"Draw",v:pct.draw},{s:"Away",v:pct.away}]){const n=num(x.v);if(n!==null){const p=n/100;rows.push({match_id:m.id,market_id:pmid,selection:x.s,probability:p,fair_odd:p>0?1/p:null,confidence:p,model_version:"api-football-predictions",generated_at:new Date().toISOString()})}}if(rows.length){const d=await db.from("predictions").delete().eq("match_id",m.id);if(d.error)throw d.error;const ins=await db.from("predictions").insert(rows);if(ins.error)throw ins.error;predictionsSaved+=rows.length}}
   const books=Array.isArray(or?.response?.[0]?.bookmakers)?or.response[0].bookmakers:[];const orows:any[]=[];for(const book of books){const bookmaker=clean(book?.name??book?.id??"Unknown");for(const bet of book?.bets??[]){const name=clean(bet?.name).toLowerCase();for(const v of bet?.values??[]){const value=clean(v?.value),low=value.toLowerCase();let code:string|null=null;if((name.includes("match winner")||name.includes("1x2"))&&["home","draw","away"].includes(low))code="MATCH_RESULT";else if(name.includes("both teams")&&low.includes("yes"))code="BTTS_YES";else if((name.includes("over/under")||name.includes("goals over/under"))&&low.includes("over 1.5"))code="OVER_1_5";else if((name.includes("over/under")||name.includes("goals over/under"))&&low.includes("over 2.5"))code="OVER_2_5";else if(name.includes("corner")&&low.includes("over 7.5"))code="CORNERS_OVER_7_5";else if(name.includes("corner")&&low.includes("over 8.5"))code="CORNERS_OVER_8_5";else if(name.includes("corner")&&low.includes("over 9.5"))code="CORNERS_OVER_9_5";const mid=code?mids.get(code):null,odd=num(v?.odd);if(mid&&odd!==null&&odd>1)orows.push({match_id:m.id,market_id:mid,bookmaker,selection:value,line:v?.handicap!=null?num(v.handicap):null,odd,observed_at:new Date().toISOString(),external_id:`${ext}-${bookmaker}-${bet?.id??name}-${value}-${v?.handicap??""}`})}}}if(orows.length){const ins=await db.from("odds").insert(orows);if(ins.error)throw ins.error;oddsSaved+=orows.length}
   const statRows:any[]=[];for(const teamStat of Array.isArray(st?.response)?st.response:[]){const teamExt=String(teamStat?.team?.id??"");if(!teamExt)continue;const {data:team}=await db.from("teams").select("id").eq("external_id",teamExt).maybeSingle();if(!team)continue;const vals:any={};for(const item of teamStat?.statistics??[]){vals[String(item?.type??"").toLowerCase()]=item?.value}statRows.push({match_id:m.id,team_id:team.id,possession:num(vals["ball possession"]),shots:num(vals["total shots"]),shots_on_target:num(vals["shots on goal"]),corners:num(vals["corner kicks"]),yellow_cards:num(vals["yellow cards"]),red_cards:num(vals["red cards"]),fouls:num(vals["fouls"]),offsides:num(vals["offsides"])})}if(statRows.length){const del=await db.from("match_stats").delete().eq("match_id",m.id);if(del.error)throw del.error;const ins=await db.from("match_stats").insert(statRows);if(ins.error)throw ins.error;statsSaved+=statRows.length}processed++
  }catch(e){errors.push({fixture:ext,source:"database",error:e instanceof Error?e.message:String(e)})}
 }
 return out({ok:true,partial:errors.length>0,action,user_id:user.id,requested:ids.length,resolved:resolved.length,processed,predictions_saved:predictionsSaved,odds_saved:oddsSaved,stats_saved:statsSaved,active_market_codes:Array.from(mids.keys()),samples,errors:errors.slice(0,50)});
});