import React,{useCallback,useEffect,useMemo,useState} from 'react'
import Auth from './components/Auth'
import {supabase} from './lib/supabase'

const TZ='America/Bogota'
const MARKET={result:'1X2',btts:'BTTS',over_under:'Over/Under',corners:'Corners',cards:'Cards',shots:'Shots',shots_on_target:'Shots on Target'}
const TOP5=['English Premier League','Spanish La Liga','German Bundesliga','Italian Serie A','French Ligue 1']
const EUROPE=['England','Spain','Germany','Italy','France','Netherlands','Belgium','Portugal','Scotland','Turkey','Denmark','Sweden','Poland','Austria','Croatia','Switzerland','Greece','Norway','Czech Republic','Czechia']
const SOUTH_AMERICA=['Argentina','Brazil','Colombia','Chile','Uruguay','Paraguay','Ecuador','Peru','Bolivia','Venezuela']
const norm=s=>String(s??'').toLowerCase().replace(/[^a-z0-9]+/g,'_')
const pct=v=>`${(Number(v)*100).toFixed(1)}%`
const dateFmt=(v,time=false)=>{const d=new Date(v);if(Number.isNaN(d.getTime()))return '—';return new Intl.DateTimeFormat('es-CO',time?{hour:'2-digit',minute:'2-digit',timeZone:TZ}:{day:'2-digit',month:'short',year:'numeric',timeZone:TZ}).format(d)}

export default function AppFixed2(){
 const[session,setSession]=useState(null),[ready,setReady]=useState(false),[page,setPage]=useState('dashboard')
 const[leagues,setLeagues]=useState([]),[teams,setTeams]=useState([]),[matches,setMatches]=useState([]),[markets,setMarkets]=useState([]),[predictions,setPredictions]=useState([]),[odds,setOdds]=useState([]),[statsCount,setStatsCount]=useState(0)
 const[dateRange,setDateRange]=useState('7'),[leagueGroup,setLeagueGroup]=useState('all'),[league,setLeague]=useState(''),[market,setMarket]=useState('all'),[playerProp,setPlayerProp]=useState('any')
 const[minProb,setMinProb]=useState(70),[minOdd,setMinOdd]=useState(1.3),[maxOdd,setMaxOdd]=useState(2.2)
 const[accaMode,setAccaMode]=useState('normal'),[pickCount,setPickCount]=useState(4),[dayPickCount,setDayPickCount]=useState(5)
 const[accaTargetMode,setAccaTargetMode]=useState('preset'),[accaTarget,setAccaTarget]=useState(5),[manualTarget,setManualTarget]=useState(10)
 const[syncing,setSyncing]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[diagnostic,setDiagnostic]=useState(null)

 const load=useCallback(async()=>{if(!supabase)return;const[a,b,c,m,d,e,f]=await Promise.all([
  supabase.from('leagues').select('id,name,country').order('name'),
  supabase.from('matches').select('id,league_id,home_team_id,away_team_id,kickoff_at,status,home_score,away_score,external_id').order('kickoff_at',{ascending:true}).limit(5000),
  supabase.from('teams').select('id,name').limit(5000),
  supabase.from('markets').select('id,code,name,category,is_active').eq('is_active',true).order('id'),
  supabase.from('predictions').select('id,match_id,market_id,selection,probability,fair_odd,confidence,model_version,generated_at').order('generated_at',{ascending:false}).limit(10000),
  supabase.from('odds').select('id,match_id,market_id,bookmaker,selection,line,odd,observed_at').order('observed_at',{ascending:false}).limit(20000),
  supabase.from('match_stats').select('id',{count:'exact',head:true})
 ]);const bad=[a,b,c,m,d,e,f].find(x=>x.error);if(bad){setError(bad.error.message);return}setLeagues(a.data||[]);setMatches(b.data||[]);setTeams(c.data||[]);setMarkets(m.data||[]);setPredictions(d.data||[]);setOdds(e.data||[]);setStatsCount(f.count||0)},[])
 useEffect(()=>{if(!supabase){setReady(true);return}let active=true;supabase.auth.getSession().then(({data})=>{if(active){setSession(data?.session||null);setReady(true)}});const{data:{subscription}}=supabase.auth.onAuthStateChange((_event,s)=>active&&setSession(s));return()=>{active=false;subscription.unsubscribe()}},[])
 useEffect(()=>{if(session)load()},[session,load])

 const leagueMap=useMemo(()=>new Map(leagues.map(x=>[String(x.id),x.name])),[leagues])
 const teamMap=useMemo(()=>new Map(teams.map(x=>[String(x.id),x.name])),[teams])
 const marketMap=useMemo(()=>new Map(markets.map(x=>[String(x.id),{code:x.code,name:x.name,category:x.category}])),[markets])
 const marketCode=id=>norm(marketMap.get(String(id))?.code||marketMap.get(String(id))?.name||'')
 const marketName=id=>marketMap.get(String(id))?.name||MARKET[marketCode(id)]||`Mercado #${id}`
 const now=useMemo(()=>new Date(),[])

 const bounds=useMemo(()=>{const start=new Date();start.setHours(0,0,0,0);const end=new Date(start);if(dateRange==='today')end.setDate(end.getDate()+1);else if(dateRange==='tomorrow'){start.setDate(start.getDate()+1);end.setDate(end.getDate()+1)}else if(/^next_\d+$/.test(dateRange))end.setDate(end.getDate()+Number(dateRange.split('_')[1])+1);else end.setFullYear(end.getFullYear()+1);return{start,end}},[dateRange])
 const leagueMatches=useCallback(m=>{if(league&&String(m.league_id)!==String(league))return false;if(leagueGroup==='all')return true;const name=leagueMap.get(String(m.league_id))||'';const l=leagues.find(x=>String(x.id)===String(m.league_id));const country=l?.country||'';if(leagueGroup==='top5')return TOP5.some(x=>norm(name)===norm(x));if(leagueGroup==='europe')return EUROPE.some(x=>norm(country).includes(norm(x)))||TOP5.some(x=>norm(name)===norm(x));if(leagueGroup==='south_america')return SOUTH_AMERICA.some(x=>norm(country).includes(norm(x)));return true},[league,leagueGroup,leagueMap,leagues])
 const upcoming=useMemo(()=>matches.filter(m=>{const d=new Date(m.kickoff_at);return d>=bounds.start&&d<bounds.end&&d>now&&leagueMatches(m)}).sort((a,b)=>new Date(a.kickoff_at)-new Date(b.kickoff_at)),[matches,bounds,now,leagueMatches])
 const finished=useMemo(()=>matches.filter(m=>m.home_score!=null&&m.away_score!=null&&leagueMatches(m)).sort((a,b)=>new Date(b.kickoff_at)-new Date(a.kickoff_at)),[matches,leagueMatches])
 const live=matches.filter(m=>['LIVE','1H','2H','HT','IN PLAY'].includes(String(m.status||'').toUpperCase())).length

 const playerPropMatches=p=>{if(marketCode(p.market_id)!=='player_props')return false;if(playerProp==='any')return true;const s=norm(p.selection);const keys={shots:['shot','shots','disparo','disparos'],shots_on_target:['shot_on_target','shots_on_target','on_target','a_puerta','puerta'],assists:['assist','asistencia'],goals:['goal','gol','goals'],cards:['card','tarjeta'],fouls:['foul','falta','faltas']};return(keys[playerProp]||[]).some(k=>s.includes(norm(k)))}
 const marketMatches=p=>market==='all'?true:market==='player_props'?playerPropMatches(p):marketCode(p.market_id)===market
 const filteredPredictions=useMemo(()=>predictions.filter(p=>{const m=matches.find(x=>String(x.id)===String(p.match_id));if(!m)return false;const d=new Date(m.kickoff_at);if(d<bounds.start||d>=bounds.end||d<=now)return false;if(!leagueMatches(m))return false;return marketMatches(p)}),[predictions,matches,bounds,now,leagueMatches,market,playerProp,marketMap])

 const candidateRows=useMemo(()=>{const best=new Map();for(const o of odds){const key=`${o.match_id}|${String(o.market_id)}|${norm(o.selection)}|${o.line??''}`;if(!best.has(key)||Number(o.odd)>Number(best.get(key).odd))best.set(key,o)}return filteredPredictions.map(p=>{const key=[...best.keys()].find(k=>k.startsWith(`${p.match_id}|${String(p.market_id)}|${norm(p.selection)}|`));const o=key?best.get(key):null;return o?{p,o}:null}).filter(Boolean).filter(x=>Number(x.p.probability)>=minProb/100&&Number(x.o.odd)>=minOdd&&Number(x.o.odd)<=maxOdd).sort((a,b)=>Number(b.p.probability)-Number(a.p.probability))},[filteredPredictions,odds,minProb,minOdd,maxOdd])
 const target=accaTargetMode==='manual'?Math.min(200,Math.max(5,Number(manualTarget)||5)):Number(accaTarget)
 const accaMin=Math.max(5,Math.min(200,target*0.9)),accaMax=Math.min(200,target*1.1)
 const activePickCount=accaMode==='day'?dayPickCount:pickCount
 const accas=useMemo(()=>{const rows=candidateRows,results=[];const walk=(start,picks,total,used)=>{if(picks.length===activePickCount){if(total>=accaMin&&total<=accaMax)results.push({picks:[...picks],total});return}for(let i=start;i<rows.length;i++){const r=rows[i];if(used.has(String(r.p.match_id)))continue;const next=total*Number(r.o.odd);if(next>accaMax)continue;used.add(String(r.p.match_id));picks.push(r);walk(i+1,picks,next,used);picks.pop();used.delete(String(r.p.match_id));if(results.length>=30)return}};walk(0,[],1,new Set());return results.sort((a,b)=>Math.abs(a.total-target)-Math.abs(b.total-target)).slice(0,10)},[candidateRows,activePickCount,accaMin,accaMax,target])

 async function sync(){if(syncing||!supabase)return;setSyncing(true);setError('');setMessage('Sincronizando TheSportsDB Premium: hoy + próximos 7 días…');setDiagnostic(null);try{const r=await supabase.functions.invoke('thesportsdb-sync',{body:{action:'sync_all'}});if(r.error)throw r.error;await load();setDiagnostic(r.data||{});setMessage(`Sincronización terminada: ${r.data?.matches_saved??0} partidos procesados.`)}catch(e){setError(e?.message||String(e));setMessage('')}finally{setSyncing(false)}}
 async function signOut(){await supabase?.auth.signOut();setSession(null)}
 const nav=[['dashboard','⌂ Dashboard'],['matches','⚽ Partidos'],['predictions','◈ Predicciones'],['acca','▦ ACCA Builder'],['stats','◒ Estadísticas'],['history','◷ Historial']]
 const dateLabel={today:'Hoy',tomorrow:'Mañana',next_3:'Próximos 3 días',next_4:'Próximos 4 días',next_5:'Próximos 5 días',next_6:'Próximos 6 días',next_7:'Próximos 7 días',all:'Todos los próximos'}[dateRange]||'Próximos 7 días'
 const groupLabel={all:'Todas las ligas',top5:'Top 5 ligas',europe:'Ligas europeas',south_america:'Ligas sudamericanas'}[leagueGroup]||'Todas las ligas'
 const marketLabel={all:'Todos los mercados',result:'1X2',btts:'BTTS',over_under:'Over/Under',corners:'Corners',cards:'Cards',shots:'Shots',shots_on_target:'Shots on Target',player_props:'Props de jugadores'}[market]||market
 const propLabel={any:'Cualquier prop',shots:'Tiros de jugadores',shots_on_target:'Tiros a puerta de jugadores',assists:'Asistencias',goals:'Goles',cards:'Tarjetas',fouls:'Faltas cometidas'}[playerProp]
 const accaLabel=target===200?'≈200':`≈${target}`
 function Stat({label,value,sub}){return <div className="stat"><small>{label}</small><strong>{value}</strong><em>{sub}</em></div>}
 function Filters(){return <div className="filters">
  <select value={dateRange} onChange={e=>setDateRange(e.target.value)}><option value="today">Hoy</option><option value="tomorrow">Mañana</option>{[3,4,5,6,7].map(n=><option key={n} value={`next_${n}`}>Próximos {n} días</option>)}<option value="all">Todos los próximos</option></select>
  <select value={leagueGroup} onChange={e=>{setLeagueGroup(e.target.value);setLeague('')}}><option value="all">Todas las ligas</option><option value="top5">Top 5 ligas</option><option value="europe">Ligas europeas</option><option value="south_america">Ligas sudamericanas</option></select>
  <select value={league} onChange={e=>{setLeague(e.target.value);setLeagueGroup('all')}}><option value="">Liga individual</option>{leagues.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select>
  <select value={market} onChange={e=>setMarket(e.target.value)}><option value="all">Todos los mercados</option><option value="result">1X2</option><option value="btts">BTTS</option><option value="over_under">Over/Under</option><option value="corners">Corners</option><option value="cards">Cards</option><option value="shots">Shots</option><option value="shots_on_target">Shots on Target</option><option value="player_props">Props de jugadores</option></select>
  <select value={playerProp} onChange={e=>{setPlayerProp(e.target.value);setMarket('player_props')}}><option value="any">Cualquier prop de jugador</option><option value="shots">Tiros de jugadores</option><option value="shots_on_target">Tiros a puerta de jugadores</option><option value="assists">Asistencias</option><option value="goals">Goles</option><option value="cards">Tarjetas</option><option value="fouls">Faltas cometidas</option></select>
  <label>Prob. mínima <input type="number" min="50" max="99" value={minProb} onChange={e=>setMinProb(Math.min(99,Math.max(50,Number(e.target.value)||70)))}/> %</label>
  <label>Cuota individual <input type="number" step="0.01" min="1.01" value={minOdd} onChange={e=>setMinOdd(Number(e.target.value)||1.3)}/> – <input type="number" step="0.01" min="1.01" value={maxOdd} onChange={e=>setMaxOdd(Number(e.target.value)||2.2)}/></label>
  <label>Cuota ACCA aproximada</label>
  <select value={accaTargetMode==='manual'?'manual':String(accaTarget)} onChange={e=>{if(e.target.value==='manual')setAccaTargetMode('manual');else{setAccaTargetMode('preset');setAccaTarget(Number(e.target.value))}}}>{Array.from({length:196},(_,i)=>i+5).map(n=><option key={n} value={n}>≈ {n}</option>)}<option value="manual">Manual</option></select>
  {accaTargetMode==='manual'&&<input aria-label="Cuota ACCA aproximada manual" type="number" step="0.1" min="5" max="200" value={manualTarget} onChange={e=>setManualTarget(Math.min(200,Math.max(5,Number(e.target.value)||5)))} placeholder="5–200"/>}
  <select value={accaMode} onChange={e=>setAccaMode(e.target.value)}><option value="normal">ACCA normal</option><option value="day">ACCA del día</option></select>
  {accaMode==='day'?<select value={dayPickCount} onChange={e=>setDayPickCount(Number(e.target.value))}>{Array.from({length:6},(_,i)=>i+5).map(n=><option key={n} value={n}>{n} selecciones</option>)}</select>:<select value={pickCount} onChange={e=>setPickCount(Number(e.target.value))}>{Array.from({length:9},(_,i)=>i+2).map(n=><option key={n} value={n}>{n} partidos</option>)}</select>}
 </div>}
 function Panel({title,sub,action,text,disabled,children}){return <div className="panel"><div className="title"><div><h3>{title}</h3><p>{sub}</p></div>{action&&<button onClick={action} disabled={disabled}>{text}</button>}</div>{children}</div>}
 function MatchRow({m}){return <div className="match"><div><b>{dateFmt(m.kickoff_at)}</b><small>{dateFmt(m.kickoff_at,true)}</small></div><strong>{teamMap.get(String(m.home_team_id))||`Equipo #${m.home_team_id}`}<span>{m.home_score!=null?`${m.home_score}–${m.away_score}`:'vs'}</span>{teamMap.get(String(m.away_team_id))||`Equipo #${m.away_team_id}`}</strong><label>{leagueMap.get(String(m.league_id))||'Liga'}</label><em>{m.home_score!=null?'Finalizado':'Próximo'}</em></div>}
 function Diagnostic(){if(!diagnostic)return null;return <div className="panel"><div className="title"><div><h3>Diagnóstico TheSportsDB</h3><p>Resultado real de la última ejecución</p></div></div><div className="stats"><Stat label="EVENTOS" value={diagnostic.events_fetched??0} sub="API"/><Stat label="LIGAS" value={diagnostic.leagues_saved??0} sub="nuevas"/><Stat label="EQUIPOS" value={diagnostic.teams_saved??0} sub="nuevos"/><Stat label="PARTIDOS" value={diagnostic.matches_saved??0} sub="upsert"/><Stat label="ESTADO" value={diagnostic.ok===false?'ERROR':'OK'} sub="Premium"/></div>{diagnostic.errors?.length>0&&<div className="note"><b>Errores</b>{diagnostic.errors.slice(0,10).map((e,i)=><div key={i}>{typeof e==='string'?e:JSON.stringify(e)}</div>)}</div>}</div>}
 function Empty({children}){return <div className="empty">{children}</div>}
 function content(){
  if(page==='matches')return <><Panel title="Próximos partidos" sub={`${upcoming.length} encontrados · ${dateLabel} · ${groupLabel}`} action={sync} disabled={syncing} text={syncing?'Sincronizando…':'Sincronizar TheSportsDB'}><Filters/></Panel>{upcoming.slice(0,300).map(m=><MatchRow key={m.id} m={m}/>)}{!upcoming.length&&<Empty>No hay partidos para estos filtros.</Empty>}<Diagnostic/></>
  if(page==='predictions')return <><Panel title="Predicciones" sub={`${filteredPredictions.length} registros · ${dateLabel} · ${marketLabel}${market==='player_props'?` · ${propLabel}`:''}`} action={sync} disabled={syncing} text="Actualizar datos"><Filters/></Panel>{filteredPredictions.length?filteredPredictions.slice(0,200).map(p=><div className="match" key={p.id}><div><b>{pct(p.probability)}</b><small>{p.model_version||'modelo'}</small></div><strong>Partido #{p.match_id}<span>·</span>{p.selection}</strong><label>{marketName(p.market_id)}</label><em>Fair {p.fair_odd?Number(p.fair_odd).toFixed(2):'—'}</em></div>):<Empty>No hay predicciones guardadas para estos filtros.</Empty>}<Diagnostic/></>
  if(page==='acca')return <><Panel title="ACCA Builder" sub={`${accaMode==='day'?'ACCA del día':'ACCA normal'} · ${activePickCount} ${accaMode==='day'?'selecciones':'partidos'} · probabilidad ≥ ${minProb}% · cuota individual ${minOdd.toFixed(2)}–${maxOdd.toFixed(2)} · objetivo ${accaLabel}`} action={sync} disabled={syncing} text="Actualizar datos"><Filters/></Panel>{accas.length?accas.map((a,i)=><div className="panel" key={i}><div className="title"><div><h3>{accaMode==='day'?'ACCA del día':'ACCA candidata'} #{i+1}</h3><p>{a.picks.length} selecciones · cuota total {a.total.toFixed(2)} · objetivo ≈ {target}</p></div><b className="acca-ok">CUMPLE FILTROS</b></div>{a.picks.map((r,j)=><div className="match" key={j}><div><b>{pct(r.p.probability)}</b><small>Partido #{r.p.match_id}</small></div><strong>{r.p.selection}<span>·</span>{marketName(r.p.market_id)}</strong><label>{r.o.line??'—'}</label><em>{r.o.bookmaker||'cuota'} @ {Number(r.o.odd).toFixed(2)}</em></div>)}</div>):<Empty>No existe una ACCA verificable con las cuotas y probabilidades almacenadas.</Empty>}<div className="note">Filtros: <b>{dateLabel}</b> · <b>{groupLabel}</b>{league?` · ${leagueMap.get(String(league))||'Liga seleccionada'}`:''} · <b>{marketLabel}</b>{market==='player_props'?` · ${propLabel}`:''} · probabilidad ≥ <b>{minProb}%</b> · cuota individual <b>{minOdd.toFixed(2)}–{maxOdd.toFixed(2)}</b> · cuota total objetivo <b>≈{target}</b> · rango de búsqueda <b>{accaMin.toFixed(1)}–{accaMax.toFixed(1)}</b> · <b>{activePickCount} ${accaMode==='day'?'selecciones':'partidos'}</b>.</div></>
  if(page==='stats')return <><Panel title="Estadísticas" sub="Estado de los datos en Supabase" action={sync} disabled={syncing} text="Actualizar datos"><Filters/></Panel><div className="stats"><Stat label="MATCH STATS" value={statsCount} sub="registros"/><Stat label="PREDICCIONES" value={predictions.length} sub="guardadas"/><Stat label="CUOTAS" value={odds.length} sub="observadas"/><Stat label="PARTIDOS" value={matches.length} sub="en Supabase"/></div><Diagnostic/></>
  if(page==='history')return <><Panel title="Historial" sub={`${finished.length} partidos finalizados`}><Filters/></Panel>{finished.slice(0,200).map(m=><MatchRow key={m.id} m={m}/>)}{!finished.length&&<Empty>No hay partidos finalizados para este filtro.</Empty>}</>
  return <><div className="hero"><div><label>SMART FOOTBALL ANALYTICS</label><h2>Construye ACCAs con<br/><i>datos verificables.</i></h2><p>TheSportsDB Premium = partidos, ligas, equipos, jugadores y estadísticas. Las cuotas/predicciones sólo aparecen cuando existen en Supabase.</p></div></div><div className="stats"><Stat label="PARTIDOS" value={upcoming.length} sub={dateLabel}/><Stat label="LIGAS" value={leagues.length} sub="configuradas"/><Stat label="FINALIZADOS" value={finished.length} sub="con marcador"/><Stat label="EN VIVO" value={live} sub="estado actual"/></div><Panel title="Próximos partidos" sub={`${upcoming.length} · ${dateLabel}`} action={()=>setPage('matches')} text="Ver todos"><Filters/></Panel>{upcoming.slice(0,30).map(m=><MatchRow key={m.id} m={m}/>)}<Panel title="Motor de ACCA" sub="Filtros preparados para el generador"><div className="note">Fecha: <b>{dateLabel}</b> · ligas: <b>{groupLabel}</b> · mercado: <b>{marketLabel}</b>{market==='player_props'?` · ${propLabel}`:''} · probabilidad mínima: <b>{minProb}%</b> · cuota individual: <b>{minOdd.toFixed(2)}–${maxOdd.toFixed(2)}</b> · cuota total objetivo: <b>≈{target}</b> · modo: <b>{accaMode==='day'?'ACCA del día':'ACCA normal'}</b> · selecciones/partidos: <b>{activePickCount}</b>.</div></Panel><Diagnostic/></>
 }
 if(!ready)return <div className="app"><main><div className="empty">Cargando ACCA Generator 4…</div></main></div>
 if(!session)return <div className="app"><main><Auth onAuthenticated={setSession}/></main></div>
 return <div className="app"><header><b>ACCA GENERATOR 4</b><nav>{nav.map(([id,label])=><button key={id} className={page===id?'active':''} onClick={()=>setPage(id)}>{label}</button>)}</nav><span>● Motor online v0.10</span><button onClick={signOut}>↪ Cerrar sesión</button></header><main><div className="topline"><span>CONTROL CENTER</span><span>Bogotá · GMT-5 · {session.user?.email||'usuario'}{syncing?' · SINCRONIZANDO…':''}</span></div>{message&&<div className="note">{message}</div>}{error&&<div className="alert">⚠ {error}</div>}{content()}</main></div>
}
