import React,{useCallback,useEffect,useMemo,useState} from 'react'
import Auth from './components/Auth'
import {supabase} from './lib/supabase'
const TZ='America/Bogota'
const MARKET={result:'1X2',btts:'BTTS',goals:'Over/Under',over_under:'Over/Under',corners:'Corners',cards:'Cards',shots:'Shots',shots_on_target:'Shots on Target',player_props:'Props de jugadores'}
const norm=s=>String(s??'').toLowerCase().replace(/[^a-z0-9]+/g,'_')
const pct=v=>`${(Number(v)*100).toFixed(1)}%`
const dateFmt=(v,time=false)=>{const d=new Date(v);if(Number.isNaN(d.getTime()))return '—';return new Intl.DateTimeFormat('es-CO',time?{hour:'2-digit',minute:'2-digit',timeZone:TZ}:{day:'2-digit',month:'short',year:'numeric',timeZone:TZ}).format(d)}
export default function AppFixed2(){
 const[session,setSession]=useState(null),[ready,setReady]=useState(false),[page,setPage]=useState('dashboard')
 const[leagues,setLeagues]=useState([]),[teams,setTeams]=useState([]),[matches,setMatches]=useState([]),[markets,setMarkets]=useState([]),[predictions,setPredictions]=useState([]),[odds,setOdds]=useState([]),[statsCount,setStatsCount]=useState(0)
 const[dateRange,setDateRange]=useState('7'),[league,setLeague]=useState(''),[market,setMarket]=useState('all'),[minProb,setMinProb]=useState(70),[minOdd,setMinOdd]=useState(1.3),[maxOdd,setMaxOdd]=useState(2.2),[accaMin,setAccaMin]=useState(5),[accaMax,setAccaMax]=useState(200),[pickCount,setPickCount]=useState(4)
 const[syncing,setSyncing]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[diagnostic,setDiagnostic]=useState(null)
 const load=useCallback(async()=>{if(!supabase)return;const[a,b,c,m,d,e,f]=await Promise.all([supabase.from('leagues').select('id,name,country').order('name'),supabase.from('matches').select('id,league_id,home_team_id,away_team_id,kickoff_at,status,home_score,away_score,external_id').order('kickoff_at',{ascending:true}).limit(5000),supabase.from('teams').select('id,name').limit(5000),supabase.from('markets').select('id,code,name,category,is_active').eq('is_active',true).order('id'),supabase.from('predictions').select('id,match_id,market_id,selection,probability,fair_odd,confidence,model_version,generated_at').order('generated_at',{ascending:false}).limit(10000),supabase.from('odds').select('id,match_id,market_id,bookmaker,selection,line,odd,observed_at').order('observed_at',{ascending:false}).limit(20000),supabase.from('match_stats').select('id',{count:'exact',head:true})]);const bad=[a,b,c,m,d,e,f].find(x=>x.error);if(bad){setError(bad.error.message);return}setLeagues(a.data||[]);setMatches(b.data||[]);setTeams(c.data||[]);setMarkets(m.data||[]);setPredictions(d.data||[]);setOdds(e.data||[]);setStatsCount(f.count||0)},[])
 useEffect(()=>{if(!supabase){setReady(true);return}let active=true;supabase.auth.getSession().then(({data})=>{if(active){setSession(data?.session||null);setReady(true)}});const{data:{subscription}}=supabase.auth.onAuthStateChange((_event,s)=>active&&setSession(s));return()=>{active=false;subscription.unsubscribe()}},[])
 useEffect(()=>{if(session)load()},[session,load])
 const leagueMap=useMemo(()=>new Map(leagues.map(x=>[String(x.id),x.name])),[leagues]),teamMap=useMemo(()=>new Map(teams.map(x=>[String(x.id),x.name])),[teams]),marketMap=useMemo(()=>new Map(markets.map(x=>[String(x.id),{code:x.code,name:x.name,category:x.category}])),[markets])
 const marketCode=id=>norm(marketMap.get(String(id))?.code||marketMap.get(String(id))?.name||'')
 const marketName=id=>marketMap.get(String(id))?.name||MARKET[marketCode(id)]||`Mercado #${id}`
 const now=useMemo(()=>new Date(),[])
 const bounds=useMemo(()=>{const start=new Date();start.setHours(0,0,0,0);const end=new Date(start);if(dateRange==='today')end.setDate(end.getDate()+1);else if(dateRange==='tomorrow'){start.setDate(start.getDate()+1);end.setDate(end.getDate()+1)}else if(dateRange==='7')end.setDate(end.getDate()+7);else end.setFullYear(end.getFullYear()+1);return{start,end}},[dateRange])
 const upcoming=useMemo(()=>matches.filter(m=>{const d=new Date(m.kickoff_at);return d>=bounds.start&&d<bounds.end&&d>now&&(!league||String(m.league_id)===String(league))}).sort((a,b)=>new Date(a.kickoff_at)-new Date(b.kickoff_at)),[matches,bounds,league,now])
 const finished=useMemo(()=>matches.filter(m=>m.home_score!=null&&m.away_score!=null&&(!league||String(m.league_id)===String(league))).sort((a,b)=>new Date(b.kickoff_at)-new Date(a.kickoff_at)),[matches,league])
 const live=matches.filter(m=>['LIVE','1H','2H','HT','IN PLAY'].includes(String(m.status||'').toUpperCase())).length
 const filteredPredictions=useMemo(()=>predictions.filter(p=>{const m=matches.find(x=>String(x.id)===String(p.match_id));if(!m)return false;const d=new Date(m.kickoff_at);if(d<bounds.start||d>=bounds.end||d<=now)return false;if(league&&String(m.league_id)!==String(league))return false;return market==='all'||marketCode(p.market_id)===market}),[predictions,matches,bounds,league,market,now,marketMap])
 const candidateRows=useMemo(()=>{const best=new Map();for(const o of odds){const key=`${o.match_id}|${String(o.market_id)}|${norm(o.selection)}|${o.line??''}`;if(!best.has(key)||Number(o.odd)>Number(best.get(key).odd))best.set(key,o)}return filteredPredictions.map(p=>{const key=[...best.keys()].find(k=>k.startsWith(`${p.match_id}|${String(p.market_id)}|${norm(p.selection)}|`));const o=key?best.get(key):null;return o?{p,o}:null}).filter(Boolean).filter(x=>Number(x.p.probability)>=minProb/100&&Number(x.o.odd)>=minOdd&&Number(x.o.odd)<=maxOdd).sort((a,b)=>Number(b.p.probability)-Number(a.p.probability))},[filteredPredictions,odds,minProb,minOdd,maxOdd])
 const accas=useMemo(()=>{const rows=candidateRows,results=[];const walk=(start,picks,total,used)=>{if(picks.length===pickCount){if(total>=accaMin&&total<=accaMax)results.push({picks:[...picks],total});return}for(let i=start;i<rows.length;i++){const r=rows[i];if(used.has(String(r.p.match_id)))continue;const next=total*Number(r.o.odd);if(next>accaMax)continue;used.add(String(r.p.match_id));picks.push(r);walk(i+1,picks,next,used);picks.pop();used.delete(String(r.p.match_id));if(results.length>=30)return}};walk(0,[],1,new Set());return results.sort((a,b)=>Math.abs(a.total-(accaMin+accaMax)/2)-Math.abs(b.total-(accaMin+accaMax)/2)).slice(0,10)},[candidateRows,pickCount,accaMin,accaMax])
 async function sync(){if(syncing||!supabase)return;setSyncing(true);setError('');setMessage('Sincronizando TheSportsDB Premium: hoy + próximos 7 días…');setDiagnostic(null);try{const r=await supabase.functions.invoke('thesportsdb-sync',{body:{action:'sync_all'}});if(r.error)throw r.error;await load();setDiagnostic(r.data||{});setMessage(`Sincronización terminada: ${r.data?.matches_saved??0} partidos procesados.`)}catch(e){setError(e?.message||String(e));setMessage('')}finally{setSyncing(false)}}
 async function signOut(){await supabase?.auth.signOut();setSession(null)}
 const nav=[['dashboard','⌂ Dashboard'],['matches','⚽ Partidos'],['predictions','◈ Predicciones'],['acca','▦ ACCA Builder'],['stats','◒ Estadísticas'],['history','◷ Historial']]
 const dateLabel=dateRange==='today'?'Hoy':dateRange==='tomorrow'?'Mañana':dateRange==='7'?'Próximos 7 días':'Todos los próximos'
 function Stat({label,value,sub}){return <div className="stat"><small>{label}</small><strong>{value}</strong><em>{sub}</em></div>}
 function Filters(){return <div className="filters"><select value={dateRange} onChange={e=>setDateRange(e.target.value)}><option value="today">Hoy</option><option value="tomorrow">Mañana</option><option value="7">Próximos 7 días</option><option value="all">Todos los próximos</option></select><select value={league} onChange={e=>setLeague(e.target.value)}><option value="">Todas las ligas</option>{leagues.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select><select value={market} onChange={e=>setMarket(e.target.value)}><option value="all">Todos los mercados</option><option value="result">1X2</option><option value="btts">BTTS</option><option value="over_under">Over/Under</option><option value="corners">Corners</option><option value="cards">Cards</option><option value="shots">Shots</option><option value="shots_on_target">Shots on Target</option><option value="player_props">Props de jugadores</option></select><label>Prob. mínima <input type="number" min="50" max="99" value={minProb} onChange={e=>setMinProb(Math.min(99,Math.max(50,Number(e.target.value)||70)))}/> %</label><label>Cuota individual <input type="number" step="0.01" min="1.01" value={minOdd} onChange={e=>setMinOdd(Number(e.target.value)||1.3)}/> – <input type="number" step="0.01" min="1.01" value={maxOdd} onChange={e=>setMaxOdd(Number(e.target.value)||2.2)}/></label><label>Cuota total ACCA <input type="number" step="0.1" min="1" value={accaMin} onChange={e=>setAccaMin(Number(e.target.value)||5)}/> – <input type="number" step="0.1" min="1" value={accaMax} onChange={e=>setAccaMax(Number(e.target.value)||200)}/></label><select value={pickCount} onChange={e=>setPickCount(Number(e.target.value))}>{Array.from({length:9},(_,i)=>i+2).map(n=><option key={n} value={n}>{n} partidos</option>)}</select></div>}
 function Panel({title,sub,action,text,disabled,children}){return <div className="panel"><div className="title"><div><h3>{title}</h3><p>{sub}</p></div>{action&&<button onClick={action} disabled={disabled}>{text}</button>}</div>{children}</div>}
 function MatchRow({m}){return <div className="match"><div><b>{dateFmt(m.kickoff_at)}</b><small>{dateFmt(m.kickoff_at,true)}</small></div><strong>{teamMap.get(String(m.home_team_id))||`Equipo #${m.home_team_id}`}<span>{m.home_score!=null?`${m.home_score}–${m.away_score}`:'vs'}</span>{teamMap.get(String(m.away_team_id))||`Equipo #${m.away_team_id}`}</strong><label>{leagueMap.get(String(m.league_id))||'Liga'}</label><em>{m.home_score!=null?'Finalizado':'Próximo'}</em></div>}
 function Diagnostic(){if(!diagnostic)return null;return <div className="panel"><div className="title"><div><h3>Diagnóstico TheSportsDB</h3><p>Resultado real de la última ejecución</p></div></div><div className="stats"><Stat label="EVENTOS" value={diagnostic.events_fetched??0} sub="API"/><Stat label="LIGAS" value={diagnostic.leagues_saved??0} sub="nuevas"/><Stat label="EQUIPOS" value={diagnostic.teams_saved??0} sub="nuevos"/><Stat label="PARTIDOS" value={diagnostic.matches_saved??0} sub="upsert"/><Stat label="ESTADO" value={diagnostic.ok===false?'ERROR':'OK'} sub="Premium"/></div>{diagnostic.errors?.length>0&&<div className="note"><b>Errores</b>{diagnostic.errors.slice(0,10).map((e,i)=><div key={i}>{typeof e==='string'?e:JSON.stringify(e)}</div>)}</div>}</div>}
 function Empty({children}){return <div className="empty">{children}</div>}
 function content(){
  if(page==='matches')return <><Panel title="Próximos partidos" sub={`${upcoming.length} encontrados · ${dateLabel}`} action={sync} disabled={syncing} text={syncing?'Sincronizando…':'Sincronizar TheSportsDB'}><Filters/></Panel>{upcoming.slice(0,300).map(m=><MatchRow key={m.id} m={m}/>)}{!upcoming.length&&<Empty>No hay partidos para estos filtros.</Empty>}<Diagnostic/></>
  if(page==='predictions')return <><Panel title="Predicciones" sub={`${filteredPredictions.length} registros · Supabase`} action={sync} disabled={syncing} text="Actualizar datos"><Filters/></Panel>{filteredPredictions.length?filteredPredictions.slice(0,200).map(p=><div className="match" key={p.id}><div><b>{pct(p.probability)}</b><small>{p.model_version||'modelo'}</small></div><strong>Partido #{p.match_id}<span>·</span>{p.selection}</strong><label>{marketName(p.market_id)}</label><em>Fair {p.fair_odd?Number(p.fair_odd).toFixed(2):'—'}</em></div>):<Empty>No hay predicciones guardadas para estos filtros. No se fabrican probabilidades.</Empty>}<Diagnostic/></>
  if(page==='acca')return <><Panel title="ACCA Builder" sub={`Probabilidad ≥ ${minProb}% · cuota individual ${minOdd.toFixed(2)}–${maxOdd.toFixed(2)} · cuota total ${accaMin}–${accaMax} · ${pickCount} partidos`} action={sync} disabled={syncing} text="Actualizar datos"><Filters/></Panel>{accas.length?accas.map((a,i)=><div className="panel" key={i}><div className="title"><div><h3>ACCA candidata #{i+1}</h3><p>{a.picks.length} partidos · cuota total {a.total.toFixed(2)}</p></div><b className="acca-ok">CUMPLE FILTROS</b></div>{a.picks.map((r,j)=><div className="match" key={j}><div><b>{pct(r.p.probability)}</b><small>Partido #{r.p.match_id}</small></div><strong>{r.p.selection}<span>·</span>{marketName(r.p.market_id)}</strong><label>{r.o.line??'—'}</label><em>{r.o.bookmaker||'cuota'} @ {Number(r.o.odd).toFixed(2)}</em></div>)}</div>):<Empty>No existe una ACCA verificable con las cuotas y probabilidades almacenadas. TheSportsDB aporta partidos y estadísticas; no inventamos cuotas.</Empty>}<div className="note">Filtros activos: <b>{dateLabel}</b> · <b>{leagues.length} ligas</b> · probabilidad ≥ <b>{minProb}%</b> · cuota individual <b>{minOdd.toFixed(2)}–{maxOdd.toFixed(2)}</b> · cuota total <b>{accaMin}–{accaMax}</b> · <b>{pickCount} partidos</b>. Para generar una ACCA real, la tabla <b>odds</b> debe recibir cuotas de un proveedor de apuestas.</div></>
  if(page==='stats')return <><Panel title="Estadísticas" sub="Estado de los datos en Supabase" action={sync} disabled={syncing} text="Actualizar datos"><Filters/></Panel><div className="stats"><Stat label="MATCH STATS" value={statsCount} sub="registros"/><Stat label="PREDICCIONES" value={predictions.length} sub="guardadas"/><Stat label="CUOTAS" value={odds.length} sub="observadas"/><Stat label="PARTIDOS" value={matches.length} sub="en Supabase"/></div><Diagnostic/></>
  if(page==='history')return <><Panel title="Historial" sub={`${finished.length} partidos finalizados`}><Filters/></Panel>{finished.slice(0,200).map(m=><MatchRow key={m.id} m={m}/>)}{!finished.length&&<Empty>No hay partidos finalizados para este filtro.</Empty>}</>
  return <><div className="hero"><div><label>SMART FOOTBALL ANALYTICS</label><h2>Construye ACCAs con<br/><i>datos verificables.</i></h2><p>TheSportsDB Premium = partidos, ligas, equipos, jugadores y estadísticas. Las cuotas/predicciones sólo aparecen cuando existen en Supabase.</p></div></div><div className="stats"><Stat label="PARTIDOS" value={upcoming.length} sub={dateLabel}/><Stat label="LIGAS" value={leagues.length} sub="configuradas"/><Stat label="FINALIZADOS" value={finished.length} sub="con marcador"/><Stat label="EN VIVO" value={live} sub="estado actual"/></div><Panel title="Próximos partidos" sub={`${upcoming.length} · ${dateLabel}`} action={()=>setPage('matches')} text="Ver todos"><Filters/></Panel>{upcoming.slice(0,30).map(m=><MatchRow key={m.id} m={m}/>)}<Panel title="Motor de ACCA" sub="Filtros preparados para el generador"><div className="note">Fecha: <b>{dateLabel}</b> · ligas: <b>Todas</b> o selección individual · mercados: <b>1X2, BTTS, Over/Under, Corners, Cards, Shots, Shots on Target y Props de jugadores</b> · probabilidad mínima: <b>{minProb}%</b> · cuota individual: <b>{minOdd.toFixed(2)}–{maxOdd.toFixed(2)}</b> · cuota total: <b>{accaMin}–{accaMax}</b> · número de partidos: <b>{pickCount}</b>.</div></Panel><Diagnostic/></>
 }
 if(!ready)return <div className="app"><main><div className="empty">Cargando ACCA Generator 4…</div></main></div>
 if(!session)return <div className="app"><main><Auth onAuthenticated={setSession}/></main></div>
 return <div className="app"><header><b>ACCA GENERATOR 4</b><nav>{nav.map(([id,label])=><button key={id} className={page===id?'active':''} onClick={()=>setPage(id)}>{label}</button>)}</nav><span>● Motor online v0.9</span><button onClick={signOut}>↪ Cerrar sesión</button></header><main><div className="topline"><span>CONTROL CENTER</span><span>Bogotá · GMT-5 · {session.user?.email||'usuario'}{syncing?' · SINCRONIZANDO…':''}</span></div>{message&&<div className="note">{message}</div>}{error&&<div className="alert">⚠ {error}</div>}{content()}</main></div>
}
