import React,{useCallback,useEffect,useMemo,useState} from 'react'
import Auth from './components/Auth'
import {supabase} from './lib/supabase'

const TZ='America/Bogota'
const TOP5=['English Premier League','Spanish La Liga','German Bundesliga','Italian Serie A','French Ligue 1']
const EUROPE=['England','Spain','Germany','Italy','France','Netherlands','Belgium','Portugal','Scotland','Turkey','Denmark','Sweden','Poland','Austria','Croatia','Switzerland','Greece','Norway','Czech Republic','Czechia']
const SOUTH=['Argentina','Brazil','Colombia','Chile','Uruguay','Paraguay','Ecuador','Peru','Bolivia','Venezuela']
const norm=s=>String(s??'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'_')
const pct=v=>`${(Number(v)*100).toFixed(1)}%`
const fmt=(v,time=false)=>new Intl.DateTimeFormat('es-CO',time?{hour:'2-digit',minute:'2-digit',timeZone:TZ}:{day:'2-digit',month:'short',year:'numeric',timeZone:TZ}).format(new Date(v))
const MARKET_OPTIONS=[['1x2','1X2'],['btts','BTTS'],['over_1_5','Over 1.5'],['over_2_5','Over 2.5'],['corners','Corners'],['cards','Cards'],['shots','Shots'],['shots_on_target','Shots on Target']]
const PROP_OPTIONS=[['shots','Tiros de jugadores'],['shots_on_target','Tiros a puerta'],['assists','Asistencias'],['goals','Goles'],['cards','Tarjetas'],['fouls','Faltas cometidas']]

export default function AppFixed4(){
 const[session,setSession]=useState(null),[ready,setReady]=useState(false),[page,setPage]=useState('dashboard')
 const[leagues,setLeagues]=useState([]),[teams,setTeams]=useState([]),[matches,setMatches]=useState([]),[markets,setMarkets]=useState([]),[predictions,setPredictions]=useState([]),[odds,setOdds]=useState([]),[statsCount,setStatsCount]=useState(0)
 const[dateRange,setDateRange]=useState('next_7'),[leagueGroup,setLeagueGroup]=useState('all'),[league,setLeague]=useState('')
 const[marketMode,setMarketMode]=useState('all'),[selectedMarkets,setSelectedMarkets]=useState([]),[propMode,setPropMode]=useState('all'),[selectedProps,setSelectedProps]=useState([])
 const[minProb,setMinProb]=useState(70),[minOdd,setMinOdd]=useState(1.3),[maxOdd,setMaxOdd]=useState(2.1)
 const[targetMode,setTargetMode]=useState('preset'),[target,setTarget]=useState(5),[manualTarget,setManualTarget]=useState(15)
 const[countMode,setCountMode]=useState('auto'),[pickCount,setPickCount]=useState(5),[dayPickCount,setDayPickCount]=useState(5),[accaMode,setAccaMode]=useState('normal'),[maxPerMatch,setMaxPerMatch]=useState(1)
 const[syncing,setSyncing]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('')

 const load=useCallback(async()=>{if(!supabase)return;const[a,b,c,m,p,o,s]=await Promise.all([
  supabase.from('leagues').select('id,name,country').order('name'),
  supabase.from('matches').select('id,league_id,home_team_id,away_team_id,kickoff_at,status,home_score,away_score,external_id').order('kickoff_at',{ascending:true}).limit(5000),
  supabase.from('teams').select('id,name').limit(5000),
  supabase.from('markets').select('id,code,name,category,is_active').eq('is_active',true).order('id'),
  supabase.from('predictions').select('id,match_id,market_id,selection,probability,fair_odd,confidence,model_version,generated_at').order('generated_at',{ascending:false}).limit(20000),
  supabase.from('odds').select('id,match_id,market_id,bookmaker,selection,line,odd,observed_at').order('observed_at',{ascending:false}).limit(30000),
  supabase.from('match_stats').select('id',{count:'exact',head:true})
 ]);const bad=[a,b,c,m,p,o,s].find(x=>x.error);if(bad){setError(bad.error.message);return}setLeagues(a.data||[]);setMatches(b.data||[]);setTeams(c.data||[]);setMarkets(m.data||[]);setPredictions(p.data||[]);setOdds(o.data||[]);setStatsCount(s.count||0)},[])
 useEffect(()=>{if(!supabase){setReady(true);return}let on=true;supabase.auth.getSession().then(({data})=>{if(on){setSession(data?.session||null);setReady(true)}});const{data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>on&&setSession(s));return()=>{on=false;subscription.unsubscribe()}},[])
 useEffect(()=>{if(session)load()},[session,load])
 const leagueMap=useMemo(()=>new Map(leagues.map(x=>[String(x.id),x])),[leagues])
 const teamMap=useMemo(()=>new Map(teams.map(x=>[String(x.id),x.name])),[teams])
 const marketMap=useMemo(()=>new Map(markets.map(x=>[String(x.id),x])),[markets])
 const now=new Date()
 const bounds=useMemo(()=>{const s=new Date();s.setHours(0,0,0,0);const e=new Date(s);if(dateRange==='today')e.setDate(e.getDate()+1);else if(dateRange==='tomorrow'){s.setDate(s.getDate()+1);e.setDate(e.getDate()+1)}else if(dateRange.startsWith('next_'))e.setDate(e.getDate()+Number(dateRange.split('_')[1])+1);else e.setFullYear(e.getFullYear()+1);return{s,e}},[dateRange])
 const inGroup=useCallback(m=>{if(league&&String(m.league_id)!==String(league))return false;if(leagueGroup==='all')return true;const l=leagueMap.get(String(m.league_id)),name=l?.name||'',country=l?.country||'';if(leagueGroup==='top5')return TOP5.some(x=>norm(x)===norm(name));if(leagueGroup==='europe')return EUROPE.some(x=>norm(country).includes(norm(x)))||TOP5.some(x=>norm(x)===norm(name));if(leagueGroup==='south')return SOUTH.some(x=>norm(country).includes(norm(x)));return true},[league,leagueGroup,leagueMap])
 const upcoming=useMemo(()=>matches.filter(m=>{const d=new Date(m.kickoff_at);return d>=bounds.s&&d<bounds.e&&d>now&&inGroup(m)}).sort((a,b)=>new Date(a.kickoff_at)-new Date(b.kickoff_at)),[matches,bounds,inGroup])
 const marketCode=id=>norm(marketMap.get(String(id))?.code||marketMap.get(String(id))?.name||'')
 const propType=p=>{const s=norm(p.selection);if(s.includes('shot_on_target')||s.includes('on_target')||s.includes('tiro_a_puerta'))return'shots_on_target';if(s.includes('assist')||s.includes('asistencia'))return'assists';if(s.includes('goal')||s.includes('gol'))return'goals';if(s.includes('card')||s.includes('tarjeta'))return'cards';if(s.includes('foul')||s.includes('falta'))return'fouls';if(s.includes('shot')||s.includes('tiro'))return'shots';return'other'}
 const marketOk=p=>{const code=marketCode(p.market_id);if(code==='player_props'||code.includes('player_prop')){if(marketMode==='all')return propMode==='all'||selectedProps.includes(propType(p));return selectedMarkets.includes('player_props')&&(propMode==='all'||selectedProps.includes(propType(p)))}if(marketMode==='all')return true;return selectedMarkets.includes(code)}
 const filtered=useMemo(()=>predictions.filter(p=>{const m=matches.find(x=>String(x.id)===String(p.match_id));if(!m)return false;const d=new Date(m.kickoff_at);return d>=bounds.s&&d<bounds.e&&d>now&&inGroup(m)&&marketOk(p)}),[predictions,matches,bounds,inGroup,marketMode,selectedMarkets,propMode,selectedProps,marketMap])
 const candidates=useMemo(()=>{const best=new Map();for(const o of odds){const k=`${o.match_id}|${o.market_id}|${norm(o.selection)}`;if(!best.has(k)||Number(o.odd)>Number(best.get(k).odd))best.set(k,o)}return filtered.map(p=>{const o=best.get(`${p.match_id}|${p.market_id}|${norm(p.selection)}`);return o?{p,o}:null}).filter(Boolean).filter(x=>Number(x.p.probability)>=minProb/100&&Number(x.o.odd)>=minOdd&&Number(x.o.odd)<=maxOdd).sort((a,b)=>Number(b.p.probability)-Number(a.p.probability))},[filtered,odds,minProb,minOdd,maxOdd])
 const desired=targetMode==='manual'?Math.min(200,Math.max(5,Number(manualTarget)||5)):target
 const fixedCount=accaMode==='day'?dayPickCount:pickCount
 const tolerance=Math.max(.5,desired*.15)
 const minTarget=Math.max(5,desired-tolerance),maxTarget=Math.min(200,desired+tolerance)
 const accas=useMemo(()=>{const out=[],wanted=countMode==='manual'?fixedCount:null
  const walk=(start,picks,total,usedCounts)=>{if((wanted&&picks.length===wanted)||(!wanted&&picks.length>=2&&total>=minTarget)){if(total>=minTarget&&total<=maxTarget){out.push({picks:[...picks],total,matches:new Set(picks.map(x=>String(x.p.match_id))).size});if(out.length>=60)return true}if(wanted)return false}
   for(let j=start;j<candidates.length;j++){const r=candidates[j],mid=String(r.p.match_id),used=usedCounts.get(mid)||0;if(used>=maxPerMatch)continue;const n=total*Number(r.o.odd);if(n>maxTarget)continue;usedCounts.set(mid,used+1);picks.push(r);if(walk(j+1,picks,n,usedCounts))return true;picks.pop();if(used===0)usedCounts.delete(mid);else usedCounts.set(mid,used)}return false}
  walk(0,[],1,new Map())
  if(!out.length&&countMode==='auto'){for(let c=2;c<=12&&!out.length;c++){const temp=[];const walk2=(start,picks,total,usedCounts)=>{if(picks.length===c){if(total>=minTarget&&total<=maxTarget)temp.push({picks:[...picks],total,matches:new Set(picks.map(x=>String(x.p.match_id))).size});return}for(let j=start;j<candidates.length&&temp.length<20;j++){const r=candidates[j],mid=String(r.p.match_id),u=usedCounts.get(mid)||0;if(u>=maxPerMatch)continue;const n=total*Number(r.o.odd);if(n>maxTarget)continue;usedCounts.set(mid,u+1);picks.push(r);walk2(j+1,picks,n,usedCounts);picks.pop();if(u)usedCounts.set(mid,u);else usedCounts.delete(mid)}};walk2(0,[],1,new Map());out.push(...temp)}}
  return out.sort((a,b)=>Math.abs(a.total-desired)-Math.abs(b.total-desired)).slice(0,10)
 },[candidates,countMode,fixedCount,desired,minTarget,maxTarget,maxPerMatch])
 const toggle=(value,setter,arr)=>setter(arr.includes(value)?arr.filter(x=>x!==value):[...arr,value])
 async function sync(){if(syncing)return;setSyncing(true);setError('');setMessage('Sincronizando TheSportsDB Premium…');try{const r=await supabase.functions.invoke('thesportsdb-sync',{body:{action:'sync_all'}});if(r.error)throw r.error;const{data:mx,error:mxErr}=await supabase.from('matches').select('external_id,kickoff_at').order('kickoff_at',{ascending:true}).limit(5000);if(mxErr)throw mxErr;const ids=(mx||[]).filter(m=>new Date(m.kickoff_at)>new Date()).slice(0,100).map(m=>m.external_id).filter(Boolean);if(ids.length){const a=await supabase.functions.invoke('thesportsdb-analysis',{body:{fixture_ids:ids}});if(a.error)throw a.error;setMessage(`Sincronización + análisis terminados: ${a.data?.predictions_saved??0} predicciones y ${a.data?.odds_saved??0} precios modelo.`)}else setMessage('Sincronización terminada.');await load()}catch(e){setError(e?.message||String(e));setMessage('')}finally{setSyncing(false)}}
 if(!ready)return <div className="app"><main className="content"><h2>Cargando…</h2></main></div>
 if(!session)return <Auth/>
 const dateLabel={today:'Hoy',tomorrow:'Mañana',next_3:'Próximos 3 días',next_4:'Próximos 4 días',next_5:'Próximos 5 días',next_6:'Próximos 6 días',next_7:'Próximos 7 días',all:'Todos los próximos'}[dateRange]
 const nav=[['dashboard','⌂ Dashboard'],['matches','⚽ Partidos'],['predictions','◈ Predicciones'],['acca','▦ ACCA Builder'],['stats','◒ Estadísticas'],['history','◷ Historial']]
 const matchName=m=>`${teamMap.get(String(m?.home_team_id))||'Local'} vs ${teamMap.get(String(m?.away_team_id))||'Visitante'}`
 return <div className="app"><aside className="sidebar"><div className="brand">⚽ <b>ACCAGENERATOR</b><small>4</small></div><nav>{nav.map(([id,label])=><button className={page===id?'active':''} onClick={()=>setPage(id)} key={id}>{label}</button>)}</nav><button className="logout" onClick={()=>supabase.auth.signOut()}>↪ Cerrar sesión</button></aside><main className="content"><div className="topline"><span>CONTROL CENTER</span><span>Bogotá · GMT-5 · {session.user.email}</span></div>{error&&<div className="alert">⚠ {error}</div>}{message&&<div className="notice">{message}</div>}
 <section className="hero"><div><label>SMART FOOTBALL ANALYTICS</label><h2>Construye ACCAs con <i>datos verificables</i>.</h2><p>TheSportsDB Premium · partidos, ligas, equipos, jugadores y estadísticas · modelo propio para predicciones y precios.</p></div></section>
 <div className="stats"><div className="stat">PARTIDOS<strong>{upcoming.length}</strong><small>{dateLabel}</small></div><div className="stat">LIGAS<strong>{leagues.length}</strong><small>configuradas</small></div><div className="stat">FINALIZADOS<strong>{matches.filter(m=>m.home_score!=null&&m.away_score!=null).length}</strong><small>con marcador</small></div><div className="stat">PREDICCIONES<strong>{predictions.length}</strong><small>modelo propio</small></div><div className="stat">PRECIOS<strong>{odds.length}</strong><small>MODEL_FAIR</small></div></div>
 <section className="panel filter-panel"><div className="title"><div><h3>Filtros del generador</h3><p>Todos son opcionales salvo el rango de cuota individual y el objetivo de ACCA.</p></div><button onClick={sync} disabled={syncing}>{syncing?'Sincronizando…':'Sincronizar + analizar'}</button></div>
 <div className="filter-grid">
 <label>Fecha<select value={dateRange} onChange={e=>setDateRange(e.target.value)}><option value="today">Hoy</option><option value="tomorrow">Mañana</option>{[3,4,5,6,7].map(n=><option key={n} value={`next_${n}`}>Próximos {n} días</option>)}<option value="all">Todos los próximos</option></select></label>
 <label>Ligas<select value={leagueGroup} onChange={e=>{setLeagueGroup(e.target.value);setLeague('')}}><option value="all">Todas las ligas</option><option value="top5">Top 5 ligas</option><option value="europe">Ligas europeas</option><option value="south">Ligas sudamericanas</option></select></label>
 <label>Liga individual<select value={league} onChange={e=>{setLeague(e.target.value);setLeagueGroup('all')}}><option value="">Cualquiera</option>{leagues.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label>
 <label>Probabilidad mínima (%)<input type="number" min="1" max="99" value={minProb} onChange={e=>setMinProb(Math.min(99,Math.max(1,Number(e.target.value)||70)))}/></label>
 <label>Cuota individual mínima<input type="number" min="1.2" max="2.5" step=".01" value={minOdd} onChange={e=>setMinOdd(Math.min(2.5,Math.max(1.2,Number(e.target.value)||1.2)))}/></label>
 <label>Cuota individual máxima<input type="number" min="1.2" max="2.5" step=".01" value={maxOdd} onChange={e=>setMaxOdd(Math.min(2.5,Math.max(1.2,Number(e.target.value)||2.1)))}/></label>
 <label>Cuota total<select value={targetMode==='manual'?'manual':target} onChange={e=>e.target.value==='manual'?setTargetMode('manual'):(setTargetMode('preset'),setTarget(Number(e.target.value)))}>{Array.from({length:196},(_,i)=><option key={i+5} value={i+5}>ACCA ≈ {i+5}</option>)}<option value="manual">Cuota aproximada manual</option></select></label>
 {targetMode==='manual'&&<label>Objetivo manual (5–200)<input type="number" min="5" max="200" step=".1" value={manualTarget} onChange={e=>setManualTarget(e.target.value)}/></label>}
 <label>Modo de selecciones<select value={countMode} onChange={e=>setCountMode(e.target.value)}><option value="auto">Automático según cuota total</option><option value="manual">Número de selecciones manual</option></select></label>
 {countMode==='manual'&&<label>Número de selecciones<select value={accaMode==='day'?dayPickCount:pickCount} onChange={e=>accaMode==='day'?setDayPickCount(Number(e.target.value)):setPickCount(Number(e.target.value))}>{Array.from({length:9},(_,i)=><option key={i+2} value={i+2}>{i+2} selecciones</option>)}</select></label>}
 <label>Máx. selecciones por partido<select value={maxPerMatch} onChange={e=>setMaxPerMatch(Number(e.target.value))}><option value="1">1</option><option value="2">2</option><option value="3">3</option><option value="4">4</option></select></label>
 <label>Tipo de ACCA<select value={accaMode} onChange={e=>setAccaMode(e.target.value)}><option value="normal">ACCA normal</option><option value="day">ACCA del día (5–10)</option></select></label>
 </div>
 <div className="filter-block"><b>Mercados</b><div className="chips"><button className={marketMode==='all'?'chip active':''} onClick={()=>{setMarketMode('all');setSelectedMarkets([])}}>Cualquiera / todos</button>{MARKET_OPTIONS.map(([v,t])=><button key={v} className={marketMode==='selected'&&selectedMarkets.includes(v)?'chip active':'chip'} onClick={()=>{setMarketMode('selected');toggle(v,setSelectedMarkets,selectedMarkets)}}>{t}</button>)}<button className={marketMode==='selected'&&selectedMarkets.includes('player_props')?'chip active':'chip'} onClick={()=>{setMarketMode('selected');toggle('player_props',setSelectedMarkets,selectedMarkets)}}>Props de jugadores</button></div></div>
 <div className="filter-block"><b>Props de jugadores</b><div className="chips"><button className={propMode==='all'?'chip active':'chip'} onClick={()=>{setPropMode('all');setSelectedProps([])}}>Cualquier prop</button>{PROP_OPTIONS.map(([v,t])=><button key={v} className={propMode==='selected'&&selectedProps.includes(v)?'chip active':'chip'} onClick={()=>{setPropMode('selected');toggle(v,setSelectedProps,selectedProps)}}>{t}</button>)}</div></div>
 <div className="filter-summary"><b>Objetivo:</b> ACCA ≈ {desired} · rango permitido {minTarget.toFixed(1)}–{maxTarget.toFixed(1)} · <b>cuota por selección:</b> {minOdd.toFixed(2)}–{maxOdd.toFixed(2)} · <b>prob. mínima:</b> {minProb}% · <b>partidos:</b> {countMode==='auto'?'automáticos':`${fixedCount} selecciones`}</div>
 </section>
 <section className="panel"><div className="title"><div><h3>Próximos partidos</h3><p>{upcoming.length} partidos disponibles en {dateLabel}</p></div></div>{upcoming.slice(0,60).map(m=><article className="match" key={m.id}><div><b>{matchName(m)}</b><small>{leagueMap.get(String(m.league_id))?.name||'—'} · {fmt(m.kickoff_at,true)} · {fmt(m.kickoff_at)}</small></div><span>Próximo</span></article>)}</section>
 {page==='predictions'&&<section className="panel"><div className="title"><h3>Predicciones filtradas</h3></div>{filtered.slice(0,100).map(p=>{const m=matches.find(x=>String(x.id)===String(p.match_id));return <article className="match" key={p.id}><div><b>{matchName(m)}</b><small>{marketMap.get(String(p.market_id))?.name||marketMap.get(String(p.market_id))?.code} · {p.selection} · {pct(p.probability)}</small></div><strong>{Number(p.fair_odd||0).toFixed(2)}</strong></article>})}</section>}
 {page==='acca'&&<section className="panel"><div className="title"><div><h3>ACCA disponibles</h3><p>Objetivo ≈ {desired}. El número de partidos se calcula automáticamente cuando está en modo automático.</p></div></div>{accas.length?accas.map((a,i)=><article className="acca" key={i}><b>ACCA #{i+1} · cuota ≈ {a.total.toFixed(2)} · {a.picks.length} selecciones · {a.matches} partidos</b>{a.picks.map((x,j)=>{const m=matches.find(z=>String(z.id)===String(x.p.match_id));return <div key={j}>{matchName(m)} · {x.p.selection} · prob. {pct(x.p.probability)} · cuota {Number(x.o.odd).toFixed(2)}</div>})}</article>):<p className="empty">No hay combinaciones con los filtros actuales. Si el objetivo es alto, el generador puede necesitar más selecciones por partido o un rango de cuota individual más amplio.</p>}</section>}
 {page==='stats'&&<section className="panel"><div className="title"><h3>Estadísticas</h3></div><p>Registros match_stats: <b>{statsCount}</b> · Predicciones: <b>{predictions.length}</b> · Precios MODEL_FAIR: <b>{odds.length}</b>.</p></section>}
 </main></div>
}
