import React,{useCallback,useEffect,useMemo,useState} from 'react'
import Auth from './components/Auth'
import {supabase} from './lib/supabase'
const TZ='America/Bogota'
const fmt=(v,time=false)=>{const d=new Date(v);if(Number.isNaN(d.getTime()))return '—';return new Intl.DateTimeFormat('es-CO',time?{hour:'2-digit',minute:'2-digit',timeZone:TZ}:{day:'2-digit',month:'short',year:'numeric',timeZone:TZ}).format(d)}
const pct=v=>`${(Number(v)*100).toFixed(1)}%`
export default function AppFixed(){
 const[session,setSession]=useState(null),[ready,setReady]=useState(false),[page,setPage]=useState('dashboard'),[leagues,setLeagues]=useState([]),[teams,setTeams]=useState([]),[matches,setMatches]=useState([]),[predictions,setPredictions]=useState([]),[odds,setOdds]=useState([]),[statsCount,setStatsCount]=useState(0),[league,setLeague]=useState(''),[minProb,setMinProb]=useState(70),[syncing,setSyncing]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[diagnostic,setDiagnostic]=useState(null)
 const load=useCallback(async()=>{if(!supabase)return;const[r1,r2,r3,r4,r5,r6]=await Promise.all([supabase.from('leagues').select('id,name,country').order('name'),supabase.from('matches').select('id,league_id,home_team_id,away_team_id,kickoff_at,status,home_score,away_score,external_id').order('kickoff_at',{ascending:true}).limit(3000),supabase.from('teams').select('id,name').limit(3000),supabase.from('predictions').select('id,match_id,market_id,selection,probability,fair_odd,confidence,model_version,generated_at').order('generated_at',{ascending:false}).limit(5000),supabase.from('odds').select('id,match_id,market_id,bookmaker,selection,line,odd,observed_at').order('observed_at',{ascending:false}).limit(10000),supabase.from('match_stats').select('id',{count:'exact',head:true})]);const e=[r1,r2,r3,r4,r5,r6].find(x=>x.error);if(e){setError(e.error.message);return}setLeagues(r1.data||[]);setMatches(r2.data||[]);setTeams(r3.data||[]);setPredictions(r4.data||[]);setOdds(r5.data||[]);setStatsCount(r6.count||0)},[])
 useEffect(()=>{if(!supabase){setReady(true);return}let a=true;supabase.auth.getSession().then(({data})=>{if(a){setSession(data?.session||null);setReady(true)}});const{data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>a&&setSession(s));return()=>{a=false;subscription.unsubscribe()}},[])
 useEffect(()=>{if(session)load()},[session,load])
 const leagueMap=useMemo(()=>new Map(leagues.map(x=>[String(x.id),x.name])),[leagues]),teamMap=useMemo(()=>new Map(teams.map(x=>[String(x.id),x.name])),[teams])
 const upcoming=useMemo(()=>matches.filter(x=>new Date(x.kickoff_at)>new Date()&&(!league||String(x.league_id)===String(league))).sort((a,b)=>new Date(a.kickoff_at)-new Date(b.kickoff_at)),[matches,league])
 const finished=useMemo(()=>matches.filter(x=>x.home_score!=null&&x.away_score!=null&&(!league||String(x.league_id)===String(league))),[matches,league])
 const live=matches.filter(x=>['LIVE','1H','2H','HT','IN PLAY'].includes(String(x.status||'').toUpperCase())).length
 const candidates=useMemo(()=>{const best=new Map();for(const o of odds){const k=`${o.match_id}|${o.market_id}|${String(o.selection).toLowerCase()}`;if(!best.has(k)||Number(o.odd)>Number(best.get(k).odd))best.set(k,o)}const rows=predictions.map(p=>{const o=best.get(`${p.match_id}|${p.market_id}|${String(p.selection).toLowerCase()}`);return o?{p,o}:null}).filter(Boolean).filter(x=>Number(x.p.probability)>=minProb/100&&Number(x.o.odd)>=1.3&&Number(x.o.odd)<=2.2);const out=[];for(let i=0;i<rows.length;i++){let total=1,picks=[],used=new Set();for(let j=i;j<rows.length&&picks.length<8;j++){const r=rows[j];if(used.has(r.p.match_id))continue;const n=total*Number(r.o.odd);if(n>200)break;picks.push(r);used.add(r.p.match_id);total=n;if(picks.length>=3&&total>=5)out.push({picks:[...picks],total})}}return out.sort((a,b)=>a.total-b.total).slice(0,5)},[predictions,odds,minProb])
 async function sync(){if(syncing)return;setSyncing(true);setMessage('Sincronizando partidos con API-Football…');setError('');setDiagnostic(null);try{const r=await supabase.functions.invoke('football-data',{body:{action:'sync_priority_leagues',season:'2026'}});if(r.error)throw r.error;await load();const{data:next,error:e}=await supabase.from('matches').select('external_id,kickoff_at').not('external_id','is',null).gt('kickoff_at',new Date().toISOString()).order('kickoff_at',{ascending:true}).limit(30);if(e)throw e;const ids=(next||[]).map(x=>String(x.external_id)).filter(Boolean);if(!ids.length){setMessage('No hay próximos fixtures con external_id.');return}setMessage(`Analizando ${ids.length} próximos fixtures…`);const a=await supabase.functions.invoke('football-analysis-v1',{body:{action:'sync_analysis',fixture_ids:ids}});if(a.error)throw a.error;setDiagnostic(a.data);setMessage(`Análisis terminado: ${a.data?.predictions_saved||0} predicciones · ${a.data?.odds_saved||0} cuotas · ${a.data?.stats_saved||0} estadísticas.`);await load()}catch(e){setError(e?.message||String(e));setMessage('')}finally{setSyncing(false)}}
 const nav=[['dashboard','⌂ Dashboard'],['matches','⚽ Partidos'],['predictions','◈ Predicciones'],['acca','▦ ACCA Builder'],['stats','◒ Estadísticas'],['history','◷ Historial']]
 const matchRow=x=><div className="match" key={x.id}><div><b>{fmt(x.kickoff_at)}</b><small>{fmt(x.kickoff_at,true)}</small></div><strong>{teamMap.get(String(x.home_team_id))||`Equipo #${x.home_team_id}`}<span>{x.home_score!=null?`${x.home_score}–${x.away_score}`:'vs'}</span>{teamMap.get(String(x.away_team_id))||`Equipo #${x.away_team_id}`}</strong><label>{leagueMap.get(String(x.league_id))||'Liga'}</label><em>{x.home_score!=null?'Finalizado':'Próximo'}</em></div>
 const diagnostics=diagnostic&&<div className="panel"><div className="title"><div><h3>Diagnóstico API-Football</h3><p>Respuesta real de la última sincronización</p></div></div><div className="stats"><Stat label="SOLICITADOS" value={diagnostic.requested||0} sub="fixtures"/><Stat label="RESUELTOS" value={diagnostic.resolved||0} sub="Supabase"/><Stat label="PREDICCIONES" value={diagnostic.predictions_saved||0} sub="guardadas"/><Stat label="CUOTAS" value={diagnostic.odds_saved||0} sub="guardadas"/></div><div className="note">Estadísticas guardadas: <b>{diagnostic.stats_saved||0}</b></div>{diagnostic.samples?.map((s,i)=><div className="note" key={i}><b>Fixture {s.fixture}</b> · Pred: HTTP {s.predictions?.http_status??s.prediction_response_items??'—'} / resultados {s.predictions?.results??0} / items {s.predictions?.response_items??s.prediction_response_items??0} · Odds: HTTP {s.odds?.http_status??'—'} / resultados {s.odds?.results??0} / items {s.odds?.response_items??s.odds_response_items??0} · Stats: HTTP {s.statistics?.http_status??'—'} / resultados {s.statistics?.results??0} / items {s.statistics?.response_items??s.statistics_response_items??0}{s.predictions?.errors&&<div>Predicción API: {JSON.stringify(s.predictions.errors)}</div>}{s.odds?.errors&&<div>Cuotas API: {JSON.stringify(s.odds.errors)}</div>}{s.statistics?.errors&&<div>Stats API: {JSON.stringify(s.statistics.errors)}</div>}</div>)}{diagnostic.errors?.length>0&&<div className="note"><b>Errores detectados</b>{diagnostic.errors.slice(0,10).map((e,i)=><div key={i}>#{i+1} {e.fixture} · {e.source} · HTTP {e.http_status||'—'} · {typeof e.error==='string'?e.error:JSON.stringify(e.error)}</div>)}</div>}</div>
 function Stat({label,value,sub}){return <div className="stat"><div><small>{label}</small><strong>{value}</strong><em>{sub}</em></div></div>}
 function Filters(){return <div className="filters"><select value={league} onChange={e=>setLeague(e.target.value)}><option value="">Todas las ligas</option>{leagues.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select><label>Prob. mínima <input type="number" min="50" max="99" value={minProb} onChange={e=>setMinProb(Number(e.target.value)||70)}/> %</label></div>}
 function Panel({title,sub,action,disabled,text,children}){return <div className="panel"><div className="title"><div><h3>{title}</h3><p>{sub}</p></div>{action&&<button onClick={action} disabled={disabled}>{text}</button>}</div>{children}</div>}
 function content(){if(page==='matches')return <><Panel title="Partidos" sub={`${upcoming.length} próximos · ${finished.length} finalizados`} action={sync} disabled={syncing} text={syncing?'Sincronizando…':'Sincronizar API-Football'}><Filters/></Panel>{upcoming.slice(0,100).map(matchRow)}{diagnostics}</>;if(page==='predictions')return <><Panel title="Predicciones" sub="API-Football · modelo del proveedor" action={sync} disabled={syncing} text="Actualizar datos"/>{predictions.length?predictions.slice(0,100).map(p=><div className="match" key={p.id}><div><b>{pct(p.probability)}</b><small>{p.model_version}</small></div><strong>Partido #{p.match_id}<span>→</span>{p.selection}</strong><label>Fair {p.fair_odd?Number(p.fair_odd).toFixed(2):'—'}</label><em>{p.confidence?pct(p.confidence)+' conf.':'—'}</em></div>):<div className="empty">No hay predicciones guardadas.</div>}{diagnostics}</>;if(page==='acca')return <><Panel title="ACCA Builder" sub={`Probabilidad mínima ${minProb}% · cuota individual 1.30–2.20 · total 5–200`} action={sync} disabled={syncing} text="Actualizar datos"/>{candidates.length?candidates.map((c,i)=><div className="panel" key={i}><h3>ACCA candidata #{i+1}</h3>{c.picks.map((r,j)=><div className="match" key={j}><strong>Partido #{r.p.match_id}<span>→</span>{r.p.selection}</strong><label>{pct(r.p.probability)}</label><em>{r.o.bookmaker} @ {Number(r.o.odd).toFixed(2)}</em></div>)}<div className="note"><b>Cuota combinada {c.total.toFixed(2)}</b> · {c.picks.length} selecciones</div></div>):<div className="empty">No existe todavía una ACCA real que cumpla los filtros.</div>}</>;if(page==='stats')return <><Panel title="Estadísticas" sub="Datos almacenados en Supabase"/><div className="stats"><Stat label="MATCH STATS" value={statsCount} sub="registros"/><Stat label="PREDICCIONES" value={predictions.length} sub="guardadas"/><Stat label="CUOTAS" value={odds.length} sub="observadas"/></div>{diagnostics}</>;if(page==='history')return <><Panel title="Historial" sub={`${finished.length} partidos finalizados`}/>{finished.slice(0,100).map(matchRow)}</>;return <><div className="hero"><div><label>SMART FOOTBALL ANALYTICS</label><h2>Construye ACCAs con<br/><i>probabilidad y valor.</i></h2><p>Datos reales de Supabase + API-Football.</p></div></div><div className="stats"><Stat label="PARTIDOS" value={matches.length} sub={`${upcoming.length} próximos`}/><Stat label="LIGAS" value={leagues.length} sub="configuradas"/><Stat label="FINALIZADOS" value={finished.length} sub="con marcador"/><Stat label="EN VIVO" value={live} sub="estado actual"/><Stat label="PREDICCIONES" value={predictions.length} sub="guardadas"/><Stat label="CUOTAS" value={odds.length} sub="observadas"/></div><Panel title={upcoming.length?'Próximos partidos':'Partidos disponibles'} sub="America/Bogota · Supabase" action={sync} disabled={syncing} text={syncing?'Sincronizando…':'Sincronizar API-Football'}><Filters/></Panel>{upcoming.slice(0,12).map(matchRow)}{diagnostics}</>}
 if(!ready)return <div className="empty">Cargando…</div>;if(!session)return <Auth/>;return <div className="app"><header><b>ACCAGENERATOR 4</b><nav>{nav.map(([k,t])=><button key={k} className={page===k?'active':''} onClick={()=>setPage(k)}>{t}</button>)}</nav><span>● Motor online v0.8</span></header><main><div className="topline"><span>CONTROL CENTER</span><span>Bogotá · GMT-5 · {session.user.email}</span></div>{message&&<div className="note">⚡ {message}</div>}{error&&<div className="note">⚠ {error}</div>}{content()}</main></div>
}