import React,{useEffect,useMemo,useState} from 'react'
import Auth from './components/Auth'
import {supabase} from './lib/supabase'
const TZ='America/Bogota',norm=v=>String(v??'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'_'),pct=v=>`${(+v*100).toFixed(1)}%`
const date=v=>new Intl.DateTimeFormat('es-CO',{day:'2-digit',month:'short',year:'numeric',timeZone:TZ}).format(new Date(v)),time=v=>new Intl.DateTimeFormat('es-CO',{hour:'2-digit',minute:'2-digit',timeZone:TZ}).format(new Date(v))
const marketList=[['all','Todos'],['1x2','1X2'],['btts','BTTS'],['over_1_5','Over 1.5'],['over_2_5','Over 2.5'],['corners','Corners'],['cards','Cards'],['shots','Shots'],['shots_on_target','Shots on Target'],['player_props','Props jugadores']]
export default function AppProductionFixed(){
 const[session,setSession]=useState(null),[ready,setReady]=useState(false),[page,setPage]=useState('dashboard'),[data,setData]=useState({leagues:[],teams:[],matches:[],markets:[],predictions:[],odds:[]}),[range,setRange]=useState(7),[league,setLeague]=useState(''),[market,setMarket]=useState('all'),[prob,setProb]=useState(70),[minOdd,setMinOdd]=useState(1.3),[maxOdd,setMaxOdd]=useState(2.2),[target,setTarget]=useState(5),[selectionCount,setSelectionCount]=useState(5),[countMode,setCountMode]=useState('auto'),[busy,setBusy]=useState(false),[msg,setMsg]=useState(''),[err,setErr]=useState('')
 const load=async()=>{const q=await Promise.all([supabase.from('leagues').select('id,name,country').order('name'),supabase.from('teams').select('id,name').limit(5000),supabase.from('matches').select('id,league_id,home_team_id,away_team_id,kickoff_at,home_score,away_score,external_id,status').order('kickoff_at').limit(5000),supabase.from('markets').select('id,code,name').eq('is_active',true),supabase.from('predictions').select('id,match_id,market_id,selection,probability,fair_odd').order('generated_at',{ascending:false}).limit(20000),supabase.from('odds').select('id,match_id,market_id,bookmaker,selection,odd').order('observed_at',{ascending:false}).limit(30000)]);const bad=q.find(x=>x.error);if(bad){setErr(bad.error.message);return false}setData({leagues:q[0].data||[],teams:q[1].data||[],matches:q[2].data||[],markets:q[3].data||[],predictions:q[4].data||[],odds:q[5].data||[]});return true}
 useEffect(()=>{let on=true;supabase.auth.getSession().then(({data})=>{if(on){setSession(data?.session||null);setReady(true)}});const{data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>on&&setSession(s));return()=>{on=false;subscription.unsubscribe()}},[])
 useEffect(()=>{if(session){load();const t=setInterval(load,60000);return()=>clearInterval(t)}},[session])
 const lm=useMemo(()=>new Map(data.leagues.map(x=>[String(x.id),x.name])),[data.leagues]),tm=useMemo(()=>new Map(data.teams.map(x=>[String(x.id),x.name])),[data.teams]),mm=useMemo(()=>new Map(data.markets.map(x=>[String(x.id),x])),[data.markets])
 const start=useMemo(()=>{const d=new Date();d.setHours(0,0,0,0);if(range===0)d.setDate(d.getDate()+1);return d},[range]),end=useMemo(()=>{const d=new Date(start);d.setDate(d.getDate()+range+1);return d},[start,range])
 const upcoming=useMemo(()=>data.matches.filter(m=>{const t=Date.parse(m.kickoff_at);return t>=+start&&t<+end&&t>Date.now()&&(!league||String(m.league_id)===String(league))}).sort((a,b)=>Date.parse(a.kickoff_at)-Date.parse(b.kickoff_at)),[data.matches,start,end,league])
 const code=id=>norm(mm.get(String(id))?.code||mm.get(String(id))?.name||''),okMarket=(c,w)=>w==='all'||c===w||c.startsWith(w+'_')
 const filtered=useMemo(()=>data.predictions.filter(p=>{const m=data.matches.find(x=>String(x.id)===String(p.match_id));if(!m)return false;const t=Date.parse(m.kickoff_at);return t>=+start&&t<+end&&t>Date.now()&&(!league||String(m.league_id)===String(league))&&okMarket(code(p.market_id),market)}),[data.predictions,data.matches,start,end,league,market,mm])
 const candidates=useMemo(()=>{const best=new Map();for(const o of data.odds){const k=`${o.match_id}|${o.market_id}|${norm(o.selection)}`;if(!best.has(k)||+o.odd>+best.get(k).odd)best.set(k,o)}return filtered.filter(p=>+p.probability>=prob/100).map(p=>{const live=best.get(`${p.match_id}|${p.market_id}|${norm(p.selection)}`),fair=+p.fair_odd,o=live&&+live.odd>=minOdd&&+live.odd<=maxOdd?live:(Number.isFinite(fair)&&fair>=minOdd&&fair<=maxOdd?{odd:fair,bookmaker:'MODEL_FAIR'}:null);return o?{p,o}:null}).filter(Boolean).sort((a,b)=>+b.p.probability-+a.p.probability)},[filtered,data.odds,prob,minOdd,maxOdd])
 const accas=useMemo(()=>{const out=[],n=countMode==='manual'?selectionCount:null,lo=countMode==='target'?Math.max(5,target*.85):5,hi=countMode==='target'?Math.min(200,target*1.15):200;const walk=(i,picks,total,used)=>{if((n?picks.length===n:picks.length>=2)&&total>=lo&&total<=hi)out.push({picks:[...picks],total});if((n&&picks.length>=n)||picks.length>=20||total>=hi||out.length>=100)return;for(let j=i;j<candidates.length&&out.length<100;j++){const r=candidates[j],id=String(r.p.match_id),nn=total*+r.o.odd;if(used.has(id)||!Number.isFinite(nn)||nn>hi)continue;used.add(id);picks.push(r);walk(j+1,picks,nn,used);picks.pop();used.delete(id)}};walk(0,[],1,new Set());return out.sort((a,b)=>countMode==='target'?Math.abs(a.total-target)-Math.abs(b.total-target):b.picks.length-a.picks.length||Math.abs(a.total-target)-Math.abs(b.total-target)).slice(0,10)},[candidates,target,selectionCount,countMode])
 const nm=m=>`${tm.get(String(m?.home_team_id))||'Local'} vs ${tm.get(String(m?.away_team_id))||'Visitante'}`
 const analyze=async ids=>{const u=[...new Set(ids.map(String).filter(Boolean))];if(!u.length)return{ps:0,os:0};let ps=0,os=0;for(let i=0;i<u.length;i+=25){const batch=u.slice(i,i+25),r=await supabase.functions.invoke('thesportsdb-analysis',{body:{fixture_ids:batch}});if(r.error)throw new Error(`${r.data?.error||r.error.message||'Edge Function de análisis falló'} · lote ${i+1}-${i+batch.length}`);if(r.data?.ok===false)throw new Error(r.data?.error||'El análisis no fue aceptado');ps+=+(r.data?.predictions_saved||0);os+=+(r.data?.odds_saved||0);setMsg(`Analizando ${Math.min(i+25,u.length)}/${u.length} · ${ps} predicciones · ${os} precios`)}await load();return{ps,os}}
 const sync=async()=>{if(busy)return;setBusy(true);setErr('');setMsg('Sincronizando TheSportsDB Premium…');try{const r=await supabase.functions.invoke('thesportsdb-sync-v2',{body:{action:'sync_all'}});if(r.error)throw new Error(r.data?.error||r.error.message||'Falló la sincronización');if(r.data?.ok===false&&!r.data?.partial)throw new Error(r.data?.error||'La sincronización no fue aceptada');await load();setMsg(`Sincronización terminada · ${r.data?.matches_saved??0} partidos actualizados${r.data?.partial?' · datos parciales':''}.`)}catch(e){setErr(e?.message||String(e));setMsg('')}finally{setBusy(false)}}
 const analyzeUpcoming=async()=>{if(busy)return;const ids=upcoming.map(m=>m.external_id).filter(Boolean);if(!ids.length){setErr('No hay partidos con external_id para analizar.');return}setBusy(true);setErr('');setMsg(`Analizando automáticamente ${ids.length} partidos…`);try{const a=await analyze(ids);setMsg(`Análisis terminado · ${a.ps} predicciones · ${a.os} precios.`)}catch(e){setErr(e?.message||String(e));setMsg('')}finally{setBusy(false)}}
 if(!ready)return <div className="app"><main className="content"><h2>Cargando…</h2></main></div>;if(!session)return <Auth/>
 const Filters=()=> <section className="panel filter-panel"><div className="title"><div><h3>Filtros del generador</h3><p>El motor selecciona automáticamente los partidos; no tienes que marcarlos uno por uno.</p></div><div><button onClick={sync} disabled={busy}>{busy?'Procesando…':'Sincronizar'}</button><button onClick={analyzeUpcoming} disabled={busy||!upcoming.length}>Analizar partidos</button></div></div><div className="filter-grid"><label>Fecha<select value={range} onChange={e=>setRange(+e.target.value)}><option value="0">Hoy</option><option value="1">Mañana</option><option value="3">Próximos 3 días</option><option value="4">Próximos 4 días</option><option value="5">Próximos 5 días</option><option value="6">Próximos 6 días</option><option value="7">Próximos 7 días</option></select></label><label>Liga<select value={league} onChange={e=>setLeague(e.target.value)}><option value="">Todas</option>{data.leagues.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label><label>Mercado<select value={market} onChange={e=>setMarket(e.target.value)}>{marketList.map(x=><option key={x[0]} value={x[0]}>{x[1]}</option>)}</select></label><label>Prob. mínima<input type="number" value={prob} min="1" max="99" onChange={e=>setProb(+e.target.value||70)}/></label><label>Cuota mínima<input type="number" value={minOdd} step=".01" onChange={e=>setMinOdd(+e.target.value||1.3)}/></label><label>Cuota máxima<input type="number" value={maxOdd} step=".01" onChange={e=>setMaxOdd(+e.target.value||2.2)}/></label><label>Modo<select value={countMode} onChange={e=>setCountMode(e.target.value)}><option value="auto">Automático según cuota total</option><option value="manual">Número de partidos</option><option value="target">Cuota total manual</option></select></label>{countMode==='manual'&&<label>Número de partidos<select value={selectionCount} onChange={e=>setSelectionCount(+e.target.value)}>{Array.from({length:19},(_,i)=><option key={i+2} value={i+2}>{i+2} partidos</option>)}</select></label>}{countMode==='target'&&<label>Cuota total<input type="number" value={target} min="5" max="200" step="1" onChange={e=>setTarget(Math.min(200,Math.max(5,+e.target.value||5)))}/></label>}</div><div className="filter-summary">{countMode==='manual'?<>Número de partidos <b>{selectionCount}</b></>:countMode==='target'?<>Cuota total objetivo <b>{target}</b></>:<>Cuota total aproximada <b>5–200</b></>} · cuota individual {minOdd.toFixed(2)}–{maxOdd.toFixed(2)} · prob. mínima {prob}% · candidatos {candidates.length}</div>{msg&&<p className="notice">{msg}</p>}{err&&<p className="error">⚠ {err}</p>}</section>
 const Matches=()=> <section className="panel"><h3>Partidos disponibles · {upcoming.length}</h3>{upcoming.slice(0,300).map(m=><article className="match" key={m.id}><div><b>{nm(m)}</b><small>{lm.get(String(m.league_id))||'—'} · {time(m.kickoff_at)} · {date(m.kickoff_at)}</small></div></article>)}{!upcoming.length&&<div className="empty">No hay partidos para este rango.</div>}</section>
 const Builder=()=> <section className="panel"><h3>ACCA Builder · {candidates.length} candidatos</h3>{accas.length?accas.map((a,i)=><article className="acca" key={i}><b>ACCA #{i+1} · {a.total.toFixed(2)} · {a.picks.length} selecciones</b>{a.picks.map((x,j)=>{const m=data.matches.find(z=>String(z.id)===String(x.p.match_id));return <div key={j}>{nm(m)} · {x.p.selection||'Selección'} · {pct(x.p.probability)} · {(+x.o.odd).toFixed(2)} · {x.o.bookmaker||'MODEL_FAIR'}</div>})}</article>):<div className="empty">No hay ACCAs con los filtros actuales. Pulsa “Analizar partidos” para generar predicciones y precios.</div>}</section>
 let body=page==='matches'?<><Filters/><Matches/></>:page==='acca'?<><Filters/><Builder/></>:page==='predictions'?<><Filters/><section className="panel"><h3>Predicciones · {filtered.length}</h3>{filtered.slice(0,300).map(p=>{const m=data.matches.find(x=>String(x.id)===String(p.match_id));return <article className="match" key={p.id}><div><b>{nm(m)}</b><small>{mm.get(String(p.market_id))?.name||code(p.market_id)} · {p.selection} · {pct(p.probability)}</small></div><strong>{(+p.fair_odd||0).toFixed(2)}</strong></article>})}</section></>:page==='history'?<><Filters/><section className="panel"><h3>Historial</h3>{data.matches.filter(m=>m.home_score!=null&&m.away_score!=null).slice(-200).reverse().map(m=><article className="match" key={m.id}><div><b>{nm(m)}</b></div><strong>{m.home_score}–{m.away_score}</strong></article>)}</section></>:<><Filters/><Builder/></>
 return <div className="app"><aside className="sidebar"><div className="brand">⚽ <b>ACCAGENERATOR</b><small>4</small></div><nav>{[['dashboard','⌂ Dashboard'],['matches','⚽ Partidos'],['predictions','◈ Predicciones'],['acca','▦ ACCA Builder'],['history','◷ Historial']].map(([id,label])=><button className={page===id?'active':''} key={id} onClick={()=>setPage(id)}>{label}</button>)}</nav><button className="logout" onClick={()=>supabase.auth.signOut()}>↪ Cerrar sesión</button></aside><main className="content"><header><div><b>CONTROL CENTER</b><span>Bogotá · GMT-5 · {session.user?.email||''}</span></div><span className="status">{busy?'● Procesando':'● Online'}</span></header><section className="hero"><h1>SMART FOOTBALL ANALYTICS</h1><p>Construye ACCAs con datos verificables.</p><small>TheSportsDB Premium · modelo propio.</small></section><div className="cards"><div><small>PARTIDOS</small><strong>{upcoming.length}</strong><span>Próximos</span></div><div><small>LIGAS</small><strong>{data.leagues.length}</strong><span>configuradas</span></div><div><small>FINALIZADOS</small><strong>{data.matches.filter(m=>m.home_score!=null&&m.away_score!=null).length}</strong><span>con marcador</span></div><div><small>PREDICCIONES</small><strong>{data.predictions.length}</strong><span>modelo propio</span></div><div><small>PRECIOS</small><strong>{data.odds.length}</strong><span>precios</span></div></div>{body}</main></div>
}
